name: PasteMe Release

on:
  release:
    types: [published]

jobs:

  release:
    if: github.repository == 'PasteUs/PasteMeLite'
    name: Release on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Update submodule
        run: |
          git submodule update --init --recursive

      - name: Gzip
        run: |
          mkdir -p pasteme_docker/frontend
          cp -r Frontend/public/usr pasteme_docker/frontend
          mkdir -p pasteme_docker/backend/config
          cp Backend/config.example.json pasteme_docker/backend/config
          cp docker-compose.yml pasteme_docker
          cp doc/DOCKER_DEPLOY.md pasteme_docker/README.md
          tar -czvf pasteme_docker.tar.gz pasteme_docker

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: pasteme_docker.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to docker branch
        run: |
          git clone https://github.com/${{ github.repository }}.git --depth=1 -b docker pasteme_buffer
          rm -rf .git
          cp -r pasteme_buffer/.git pasteme_docker
          cd pasteme_docker
          git config user.name "Lucien Shui"
          git config user.email "lucien@lucien.ink"
          git add --all
          if ! git commit -m "Release at `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"; then exit 0; fi
          git push https://"${{ secrets.GITHUB_PASSWORD }}"@"github.com/${{ github.repository }}.git" docker
